### PR TITLE
Add public cert generation instructions

### PR DESCRIPTION
**Pull request by orenyk**

### CODE REVIEW

**Comment by zachmargolis** [comment]
With this new PR, should we close out this old PR? https://github.com/18F/identity-dev-docs/pull/59

**Comment by orenyk** [comment]
@zachmargolis good question - that one is way more comprehensive, do we think it's worth expanding to include the conf file and all that?

**Comment by zachmargolis** [comment]
> that one is way more comprehensive, do we think it's worth expanding to include the conf file and all that?

If the abbreviated version is what we've been telling partners, and it works, seems good enough and less error-prone

**Review by achapm — APPROVED** [review]
👍  I like this version better because it is concise and not specific to oidc or saml. 
LGTM!

**Pull request merged**
