### PR TITLE
Document OIDC logout endpoint

### PR DESCRIPTION
**Pull request by zachmargolis**
Corresponds to: https://github.com/18F/identity-idp/pull/1437

### CODE REVIEW

**Comment by zachmargolis** [comment]
@hursey013 thanks! What do you mean about the `code` markdown not working correctly?

**Comment by hursey013** [comment]
screen shot 2017-05-19 at 1 10 56 pm

**Comment by zachmargolis** [comment]
@hursey013 I think that's just the Github formatting, on the actual page it works fine (rendered from serving this locally)

openid_connect

**Comment by hursey013** [comment]
Oops, yeah you're right. Github renders some of the code blocks correctly, but not those, I think it may want the closing ``` on it's own line? But all good if it looks correct on the rendered website!

**Pull request merged**
