### PR TITLE
LG-2606: Upgrade developer docs to newer identity-style-guide

### PR DESCRIPTION
**Pull request by zachmargolis**
This is a first pass, I was able to match most of the styles. It looks like a lot of the weights and spacing changed, and I think that's intentional? It's definitely easier to tell by spinning it up locally & tabbing between before and after

BEFORE
before-home
before-oidc

AFTER

after-home
after-oidc

### CODE REVIEW

**Comment by nickttng** [comment]
Cool. I will review more throughly.

For now, my commit pushed is to update the Dev-Docs' secondary button (that used USWDS, not Login) to match our DS' secondary button

## Before with `usa-button--secondary`

before-secondary-button

## After with `usa-button--outline`
after-secondary-button

**Comment by zachmargolis** [comment]
Perfect, thanks!

**Comment by nickttng** [comment]
Another commit with typography / spacing cleaned up (Left - Before; Right - After)

typography-cleaned-up

**Comment by zachmargolis** [comment]
> Another commit with typography / spacing cleaned up (Left - Before; Right - After)

ooo big improvement

**Comment by blacktm** [comment]
Hey folks, looking really good, nice work! Found a couple broken things however (looking at the [Federalist preview](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.app.cloud.gov/preview/18f/identity-dev-docs/margolis-upgrade-styles/) (👈to find that link, click "Show all checks" and under "federalist/build", click "Details"; you might have to have Federalist enabled on your GitHub account for that to show up):
- The "View example..." buttons, like on the [SAML guide](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.app.cloud.gov/preview/18f/identity-dev-docs/margolis-upgrade-styles/saml/), don't seem to work anymore
- The code sections have a fancy gradient, but browsers aren't rendering them properly, for example:
In Chrome (see how the colon in `format:persistent` is covered by the white overlay):
code_chrome
In Safari on macOS and iPhone (much worse as all are black):
code_safari

**Comment by zachmargolis** [comment]
Good catches, thanks! Taking a look now

**Comment by zachmargolis** [comment]
@nickttng from what I can tell, it looks like the width is messing up on the `.highlight::before` and `.hightlight::after`.... I went in the inspector in Safari and set `width` from `1rem` to `0` and it rendered fine...unsure what the goal is here?

Looks like the source is here, so we may have to patch the style guide before we merge it here?

https://github.com/18F/identity-style-guide/blob/master/src/scss/components/_code.scss#L47

**Comment by nickttng** [comment]
@zachmargolis I don't see the goal of having `1rem` beside creating the "blur/fade" effect in the before/after the code. Tmw (Fri.), we can first patch the design system (and check the `0` width effect elsewhere in the system) before merging your PR. How does this sound?

**Comment by zachmargolis** [comment]
@nickttng yup! Happy to wait for an update to style-guide

**Comment by zachmargolis** [comment]
@blacktm @nickttng updated styles fix that rendering issue on Safari! Please check this [preview link 🆒](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.app.cloud.gov/preview/18f/identity-dev-docs/margolis-upgrade-styles/saml/) and it another look!

**Comment by nickttng** [comment]
@zachmargolis Looks great. Glad @blacktm caught it.

**Comment by zachmargolis** [comment]
Agree! Great catch by @blacktm 

9e92dd8c-1f12-4426-b7ac-131dca1d294a_screenshot

**Pull request merged**
