### PR TITLE
LG-9325: Upgrade Login.gov Design System (v6.7.0)

### PR DESCRIPTION
**Pull request by aduth**
This pull request upgrades the `identity-style-guide` package from `3.0.0` to `6.7.0`.

See CHANGELOG: https://github.com/18F/identity-style-guide/blob/main/CHANGELOG.md

The main impact here is the change in default font to Public Sans, plus the removal of "Close" buttons from Accordion components on the Support page. This also removes some custom button styles which appear to be unused (`.usa-button--big`, `.usa-button--secondary`).

View live: https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.sites.pages.cloud.gov/preview/18f/identity-dev-docs/aduth-upgrade-ldgs-6/

### CODE REVIEW

**Review by nickttng — APPROVED** [review]
LGTM.

**Comment by nickttng** [comment]
@anniehirshman-gsa fysa - this update also affects the side navigation, both on desktop and mobile/tablet. the former is more obvious.

**Comment by aduth** [comment]
@anniehirshman-gsa I pushed a handful of changes based on your feedback:

- Changed the heading on the homepage from accent-cool to white
- Fix link coloring for lead content (e.g. [OpenID Connect](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.sites.pages.cloud.gov/preview/18f/identity-dev-docs/aduth-upgrade-ldgs-6/oidc/))
- Fix link coloring for autolinks (e.g. [RISC auto-discovery](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.sites.pages.cloud.gov/preview/18f/identity-dev-docs/aduth-upgrade-ldgs-6/security-events/#auto-discovery)
- Avoid emojification of footnotes (e.g. [OpenID Connect Footnotes](https://federalist-14ccf384-8bd5-4e30-aa95-a5fe5894e3c1.sites.pages.cloud.gov/preview/18f/identity-dev-docs/aduth-upgrade-ldgs-6/oidc/#footnotes))

**Review by anniehirshman-gsa — APPROVED** [review]
Looks fantastic, thanks for your help! 🎉

**Review by Jeremy1026 — APPROVED** [review]

**Pull request merged**
