### PR TITLE
Update identity-style-guide

### PR DESCRIPTION
**Pull request by ctro**

### CODE REVIEW

**Comment by ctro** [comment]
Hi @nickttng I think I updated the identity-style-guide correctly.  After update I'm seeing some errors in my console:

```
web_1  | [2020-02-13 19:35:50] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff2' not found.
web_1  | [2020-02-13 19:35:50] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff' not found.
web_1  | [2020-02-13 19:35:50] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.ttf' not found.
web_1  | [2020-02-13 19:35:52] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff2' not found.
web_1  | [2020-02-13 19:35:52] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff' not found.
web_1  | [2020-02-13 19:35:52] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.ttf' not found.
web_1  | [2020-02-13 19:35:53] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff2' not found.
web_1  | [2020-02-13 19:35:53] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff' not found.
web_1  | [2020-02-13 19:35:53] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.ttf' not found.
web_1  | [2020-02-13 19:35:54] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff2' not found.
web_1  | [2020-02-13 19:35:54] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff' not found.
web_1  | [2020-02-13 19:35:54] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.ttf' not found.
web_1  | [2020-02-13 19:35:55] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff2' not found.
web_1  | [2020-02-13 19:35:55] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.woff' not found.
web_1  | [2020-02-13 19:35:55] ERROR `/assets/fonts/merriweather/merriweather-bold-webfont.ttf' not found.
```

Wondering if you have any ideas, thanks!

**Comment by nickttng** [comment]
@ctro Wonder if it's the `assets/` vs. `src` (See screenshot of file path and naming of identity-style-guide folder). Also, `merriweather-...` vs. `Latin-Merriweather-...` 

Screen Shot 2020-02-13 at 2 02 55 PM

**Comment by nickttng** [comment]
Q: What's the difference between this PR and Zach's PR #102?

**Comment by ctro** [comment]
@nickttng this is not a burning need by any means :)
I merged the PR Zac and I were working on already.  There is code on `master` for Docker/compose (using the old identity-style-guide that is currently live on the site). 

This PR just updates the identity-style-guide to the latest, on top of the Docker work.

**Comment by ctro** [comment]
Closing this PR as a duplicate of #102 , sorry I missed that PR earlier!

**Pull request closed without merging**
